agent_type = "agent"
display_name = "Ours dev"
description = "Agent pour le développement"
safety = "yolo"
disabled_tools = []

# Auto-loaded skills
[skill]
ours-dev = true

[tools.bash]
permission = "ask"

[tools.read_file]
permission = "always"

[tools.write_file]
permission = "always"

[tools.search_replace]
permission = "always"

[tools.grep]
permission = "always"

[tools.todo]
permission = "always"
